# Generated by Django 4.2.4 on 2023-08-14 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(default='nana', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('availability_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('region', models.CharField(choices=[('ashanti', 'Ashanti Region'), ('brong', 'Brong Region'), ('central', 'Central Region '), ('eastern', 'Eastern Region '), ('greater_accra', 'Greater Accra Region'), ('northern', 'Northern Region '), ('savannah', 'Savannah Region '), ('north_east', 'North-East Region '), ('upper_east', 'Upper East Region '), ('bono_east', 'Bono East Region '), ('ahafo', 'Ahafo Region '), ('oti', 'Oti Region '), ('volta', 'Volta Region'), ('western', 'Western Region'), ('western_north', 'Western North Region'), ('upper_west', 'Upper West Region ')], max_length=20)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('education_level', models.CharField(choices=[('JHS', 'JHS'), ('SHS', 'SHS'), ('Tertiary', 'Tertiary'), ('None', 'None'), ('Other', 'Other')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sample_works', models.ImageField(blank=True, null=True, upload_to='sample_works/')),
                ('description', models.TextField(default='hello')),
                ('skills_abilities', models.TextField(default='hello')),
                ('is_approved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
