# Generated by Django 4.2.4 on 2023-08-14 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_rename_comment_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('categories', models.CharField(choices=[('Information Technology', 'Information Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Marketing and Advertising', 'Marketing and Advertising'), ('Education', 'Education'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Human Resources', 'Human Resources'), ('Art and Design', 'Art and Design'), ('Science', 'Science'), ('Construction and Trades', 'Construction and Trades'), ('Legal', 'Legal'), ('Customer Service', 'Customer Service'), ('Media and Journalism', 'Media and Journalism'), ('Transportation and Logistics', 'Transportation and Logistics'), ('Other', 'Other')], max_length=100)),
                ('regions', models.CharField(choices=[('ashanti', 'Ashanti Region'), ('brong', 'Brong Region'), ('central', 'Central Region '), ('eastern', 'Eastern Region '), ('greater_accra', 'Greater Accra Region'), ('northern', 'Northern Region '), ('savannah', 'Savannah Region '), ('north_east', 'North-East Region '), ('upper_east', 'Upper East Region '), ('bono_east', 'Bono East Region '), ('ahafo', 'Ahafo Region '), ('oti', 'Oti Region '), ('volta', 'Volta Region'), ('western', 'Western Region'), ('western_north', 'Western North Region'), ('upper_west', 'Upper West Region ')], max_length=50)),
                ('skills', models.CharField(max_length=200)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline', models.DateField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
