# Generated by Django 4.2.4 on 2023-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vacancy_email_vacancy_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(default='nana', max_length=20),
        ),
    ]
