# Generated by Django 4.2.4 on 2023-08-14 10:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_vacancy_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='telephone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('cv', models.FileField(upload_to='cv/')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vacancy')),
            ],
        ),
    ]
